### ISSUE TITLE
😎 Cool ideas

### ISSUE THREAD

**Issue by MarcoGargano** [GabAlpha/obsidian-githobs#1]
### Next features!
What we decided to integrate 😋
- [x] Add link to issue on github.com
- [x] Confirmation dialog on push
- [ ] Upload images directly to Github
- [x] Error messages
- [x] Clean repo **obsidian-sample-plugin**
	- [x] Use `GitHobs` everywhere
	- [x] It's possible to change the repo name?! 🤔

---
### Can we do it?!
...unbelievable crazy ideas 😱
- Push on save?!
	- with a dedicated setting
	- maybe you wanna save a draft on local, before pushing
- Add details to obsidian file, like properties
	- 🟢 Assignees
	- 🟢 Labels
	- `Create new`
	- Milestone
	- Projects
	- Pin

--- 
### What do we call it????

Proposals: 
- **🦤 GitHobs** ⭐️
- 🪵 GitHob
- 🦉 GabObz

### WINNER: **🦤 GitHobs**
>With dodo animal!

**Comment by zubayrrr** [comment]
Idea not directly related to this project but I think its possible to use this with https://github.com/aravindballa/github-issues-garden
